# Generated by Django 3.1.1 on 2020-09-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_auto_20200926_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='template',
            field=models.CharField(default='', max_length=200, verbose_name='Template'),
        ),
    ]
