# Generated by Django 3.1.1 on 2020-09-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='template',
            field=models.CharField(choices=[('default', 'Default'), ('image select multiple', 'Image select multiple')], default='default', max_length=200, verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='question',
            name='template',
            field=models.CharField(choices=[('default', 'Default'), ('image select multiple', 'Image select multiple')], default='default', max_length=200, verbose_name='Template'),
        ),
    ]
