# Generated by Django 3.1.1 on 2020-09-26 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0017_auto_20200926_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='template',
        ),
    ]
